services:
  app_be:
    build:
      context: .
      dockerfile: ./be/Dockerfile
    ports:
      - 8080:8080
    networks:
      - travlr_network
    environment:
      REDIS_HOST: redis-service
      REDIS_PORT: 6379
      JWT_SECRET: "${JWT_SECRET}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"

  app_fe:
    build:
      context: .
      dockerfile: ./fe/Dockerfile
    ports:
      - 3001:3000
    networks:
      - travlr_network
    environment:
      API_URL: "${API_URL}"
      BE_SERVICE_PORT: "app_be:8080"

  redis-service:
    image: redis:7.4.1
    ports:
      - 6377:6379
    volumes:
      - travlr_redis:/data
    networks:
      - travlr_network
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  travlr_redis:

networks:
  travlr_network:
    driver: bridge
