services:
  app_be:
    build:
      context: .
      dockerfile: ./be/Dockerfile
    ports:
      - 8080:8080
    networks:
      - travlr_network
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
  redis-service:
    image: redis:7.4.1
    ports:
      - 6377:6379
    volumes:
      - travlr_redis:/data
    networks:
      - travlr_network
    command: ["redis-server"]

volumes:
  travlr_redis:

networks:
  travlr_network:
    driver: bridge
